apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: pos472-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: pos472-loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: pos472-jaeger

  - name: Jaeger
    type: jaeger
    uid: pos472-jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: pos472-pg
    url: postgres:5432
    user: pos_user
    secureJsonData:
      password: pos_secret
    jsonData:
      database: pos_472
      sslmode: disable
      maxOpenConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: false
