apiVersion: 1

datasources:
  - name: POS472 PostgreSQL
    type: postgres
    uid: pos472_pg
    url: host.docker.internal:5432
    database: pos_472
    user: postgres
    secureJsonData:
      password: "123456"
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
