apiVersion: 1

datasources:
  - name: POS472 Prometheus
    type: prometheus
    uid: pos472_prom
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 15s
