import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import type { PrismaClient } from '../generated/prisma/client.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const JSON_DIR = join(__dirname, '..', '..', '..', 'docs', 'countries-master', 'json')

interface CountryJson { id: number; name: string }
interface StateJson   { id: number; id_country: number; name: string }
interface CityJson    { id: number; id_state: number; name: string }

// Mapa iso2 → datos enriquecidos de dr5hn (solo campos usados en la BD)
const DR5HN_ISO: Record<string, { iso2: string; iso3: string; phonecode: string; region: string }> = {
  "AF":{"iso2":"AF","iso3":"AFG","phonecode":"93","region":"Asia"},
  "AL":{"iso2":"AL","iso3":"ALB","phonecode":"355","region":"Europe"},
  "DZ":{"iso2":"DZ","iso3":"DZA","phonecode":"213","region":"Africa"},
  "AD":{"iso2":"AD","iso3":"AND","phonecode":"376","region":"Europe"},
  "AO":{"iso2":"AO","iso3":"AGO","phonecode":"244","region":"Africa"},
  "AG":{"iso2":"AG","iso3":"ATG","phonecode":"1268","region":"Americas"},
  "AR":{"iso2":"AR","iso3":"ARG","phonecode":"54","region":"Americas"},
  "AM":{"iso2":"AM","iso3":"ARM","phonecode":"374","region":"Asia"},
  "AU":{"iso2":"AU","iso3":"AUS","phonecode":"61","region":"Oceania"},
  "AT":{"iso2":"AT","iso3":"AUT","phonecode":"43","region":"Europe"},
  "AZ":{"iso2":"AZ","iso3":"AZE","phonecode":"994","region":"Asia"},
  "BS":{"iso2":"BS","iso3":"BHS","phonecode":"1242","region":"Americas"},
  "BH":{"iso2":"BH","iso3":"BHR","phonecode":"973","region":"Asia"},
  "BD":{"iso2":"BD","iso3":"BGD","phonecode":"880","region":"Asia"},
  "BB":{"iso2":"BB","iso3":"BRB","phonecode":"1246","region":"Americas"},
  "BY":{"iso2":"BY","iso3":"BLR","phonecode":"375","region":"Europe"},
  "BE":{"iso2":"BE","iso3":"BEL","phonecode":"32","region":"Europe"},
  "BZ":{"iso2":"BZ","iso3":"BLZ","phonecode":"501","region":"Americas"},
  "BJ":{"iso2":"BJ","iso3":"BEN","phonecode":"229","region":"Africa"},
  "BT":{"iso2":"BT","iso3":"BTN","phonecode":"975","region":"Asia"},
  "BO":{"iso2":"BO","iso3":"BOL","phonecode":"591","region":"Americas"},
  "BA":{"iso2":"BA","iso3":"BIH","phonecode":"387","region":"Europe"},
  "BW":{"iso2":"BW","iso3":"BWA","phonecode":"267","region":"Africa"},
  "BR":{"iso2":"BR","iso3":"BRA","phonecode":"55","region":"Americas"},
  "BN":{"iso2":"BN","iso3":"BRN","phonecode":"673","region":"Asia"},
  "BG":{"iso2":"BG","iso3":"BGR","phonecode":"359","region":"Europe"},
  "BF":{"iso2":"BF","iso3":"BFA","phonecode":"226","region":"Africa"},
  "BI":{"iso2":"BI","iso3":"BDI","phonecode":"257","region":"Africa"},
  "KH":{"iso2":"KH","iso3":"KHM","phonecode":"855","region":"Asia"},
  "CM":{"iso2":"CM","iso3":"CMR","phonecode":"237","region":"Africa"},
  "CA":{"iso2":"CA","iso3":"CAN","phonecode":"1","region":"Americas"},
  "CV":{"iso2":"CV","iso3":"CPV","phonecode":"238","region":"Africa"},
  "CF":{"iso2":"CF","iso3":"CAF","phonecode":"236","region":"Africa"},
  "TD":{"iso2":"TD","iso3":"TCD","phonecode":"235","region":"Africa"},
  "CL":{"iso2":"CL","iso3":"CHL","phonecode":"56","region":"Americas"},
  "CN":{"iso2":"CN","iso3":"CHN","phonecode":"86","region":"Asia"},
  "CO":{"iso2":"CO","iso3":"COL","phonecode":"57","region":"Americas"},
  "KM":{"iso2":"KM","iso3":"COM","phonecode":"269","region":"Africa"},
  "CG":{"iso2":"CG","iso3":"COG","phonecode":"242","region":"Africa"},
  "CD":{"iso2":"CD","iso3":"COD","phonecode":"243","region":"Africa"},
  "CR":{"iso2":"CR","iso3":"CRI","phonecode":"506","region":"Americas"},
  "HR":{"iso2":"HR","iso3":"HRV","phonecode":"385","region":"Europe"},
  "CU":{"iso2":"CU","iso3":"CUB","phonecode":"53","region":"Americas"},
  "CY":{"iso2":"CY","iso3":"CYP","phonecode":"357","region":"Asia"},
  "CZ":{"iso2":"CZ","iso3":"CZE","phonecode":"420","region":"Europe"},
  "DK":{"iso2":"DK","iso3":"DNK","phonecode":"45","region":"Europe"},
  "DJ":{"iso2":"DJ","iso3":"DJI","phonecode":"253","region":"Africa"},
  "DM":{"iso2":"DM","iso3":"DMA","phonecode":"1767","region":"Americas"},
  "DO":{"iso2":"DO","iso3":"DOM","phonecode":"1809","region":"Americas"},
  "EC":{"iso2":"EC","iso3":"ECU","phonecode":"593","region":"Americas"},
  "EG":{"iso2":"EG","iso3":"EGY","phonecode":"20","region":"Africa"},
  "SV":{"iso2":"SV","iso3":"SLV","phonecode":"503","region":"Americas"},
  "GQ":{"iso2":"GQ","iso3":"GNQ","phonecode":"240","region":"Africa"},
  "ER":{"iso2":"ER","iso3":"ERI","phonecode":"291","region":"Africa"},
  "EE":{"iso2":"EE","iso3":"EST","phonecode":"372","region":"Europe"},
  "ET":{"iso2":"ET","iso3":"ETH","phonecode":"251","region":"Africa"},
  "FJ":{"iso2":"FJ","iso3":"FJI","phonecode":"679","region":"Oceania"},
  "FI":{"iso2":"FI","iso3":"FIN","phonecode":"358","region":"Europe"},
  "FR":{"iso2":"FR","iso3":"FRA","phonecode":"33","region":"Europe"},
  "GA":{"iso2":"GA","iso3":"GAB","phonecode":"241","region":"Africa"},
  "GM":{"iso2":"GM","iso3":"GMB","phonecode":"220","region":"Africa"},
  "GE":{"iso2":"GE","iso3":"GEO","phonecode":"995","region":"Asia"},
  "DE":{"iso2":"DE","iso3":"DEU","phonecode":"49","region":"Europe"},
  "GH":{"iso2":"GH","iso3":"GHA","phonecode":"233","region":"Africa"},
  "GR":{"iso2":"GR","iso3":"GRC","phonecode":"30","region":"Europe"},
  "GD":{"iso2":"GD","iso3":"GRD","phonecode":"1473","region":"Americas"},
  "GT":{"iso2":"GT","iso3":"GTM","phonecode":"502","region":"Americas"},
  "GN":{"iso2":"GN","iso3":"GIN","phonecode":"224","region":"Africa"},
  "GW":{"iso2":"GW","iso3":"GNB","phonecode":"245","region":"Africa"},
  "GY":{"iso2":"GY","iso3":"GUY","phonecode":"592","region":"Americas"},
  "HT":{"iso2":"HT","iso3":"HTI","phonecode":"509","region":"Americas"},
  "HN":{"iso2":"HN","iso3":"HND","phonecode":"504","region":"Americas"},
  "HU":{"iso2":"HU","iso3":"HUN","phonecode":"36","region":"Europe"},
  "IS":{"iso2":"IS","iso3":"ISL","phonecode":"354","region":"Europe"},
  "IN":{"iso2":"IN","iso3":"IND","phonecode":"91","region":"Asia"},
  "ID":{"iso2":"ID","iso3":"IDN","phonecode":"62","region":"Asia"},
  "IR":{"iso2":"IR","iso3":"IRN","phonecode":"98","region":"Asia"},
  "IQ":{"iso2":"IQ","iso3":"IRQ","phonecode":"964","region":"Asia"},
  "IE":{"iso2":"IE","iso3":"IRL","phonecode":"353","region":"Europe"},
  "IL":{"iso2":"IL","iso3":"ISR","phonecode":"972","region":"Asia"},
  "IT":{"iso2":"IT","iso3":"ITA","phonecode":"39","region":"Europe"},
  "JM":{"iso2":"JM","iso3":"JAM","phonecode":"1876","region":"Americas"},
  "JP":{"iso2":"JP","iso3":"JPN","phonecode":"81","region":"Asia"},
  "JO":{"iso2":"JO","iso3":"JOR","phonecode":"962","region":"Asia"},
  "KZ":{"iso2":"KZ","iso3":"KAZ","phonecode":"7","region":"Asia"},
  "KE":{"iso2":"KE","iso3":"KEN","phonecode":"254","region":"Africa"},
  "KI":{"iso2":"KI","iso3":"KIR","phonecode":"686","region":"Oceania"},
  "KP":{"iso2":"KP","iso3":"PRK","phonecode":"850","region":"Asia"},
  "KR":{"iso2":"KR","iso3":"KOR","phonecode":"82","region":"Asia"},
  "KW":{"iso2":"KW","iso3":"KWT","phonecode":"965","region":"Asia"},
  "KG":{"iso2":"KG","iso3":"KGZ","phonecode":"996","region":"Asia"},
  "LA":{"iso2":"LA","iso3":"LAO","phonecode":"856","region":"Asia"},
  "LV":{"iso2":"LV","iso3":"LVA","phonecode":"371","region":"Europe"},
  "LB":{"iso2":"LB","iso3":"LBN","phonecode":"961","region":"Asia"},
  "LS":{"iso2":"LS","iso3":"LSO","phonecode":"266","region":"Africa"},
  "LR":{"iso2":"LR","iso3":"LBR","phonecode":"231","region":"Africa"},
  "LY":{"iso2":"LY","iso3":"LBY","phonecode":"218","region":"Africa"},
  "LI":{"iso2":"LI","iso3":"LIE","phonecode":"423","region":"Europe"},
  "LT":{"iso2":"LT","iso3":"LTU","phonecode":"370","region":"Europe"},
  "LU":{"iso2":"LU","iso3":"LUX","phonecode":"352","region":"Europe"},
  "MG":{"iso2":"MG","iso3":"MDG","phonecode":"261","region":"Africa"},
  "MW":{"iso2":"MW","iso3":"MWI","phonecode":"265","region":"Africa"},
  "MY":{"iso2":"MY","iso3":"MYS","phonecode":"60","region":"Asia"},
  "MV":{"iso2":"MV","iso3":"MDV","phonecode":"960","region":"Asia"},
  "ML":{"iso2":"ML","iso3":"MLI","phonecode":"223","region":"Africa"},
  "MT":{"iso2":"MT","iso3":"MLT","phonecode":"356","region":"Europe"},
  "MH":{"iso2":"MH","iso3":"MHL","phonecode":"692","region":"Oceania"},
  "MR":{"iso2":"MR","iso3":"MRT","phonecode":"222","region":"Africa"},
  "MU":{"iso2":"MU","iso3":"MUS","phonecode":"230","region":"Africa"},
  "MX":{"iso2":"MX","iso3":"MEX","phonecode":"52","region":"Americas"},
  "FM":{"iso2":"FM","iso3":"FSM","phonecode":"691","region":"Oceania"},
  "MD":{"iso2":"MD","iso3":"MDA","phonecode":"373","region":"Europe"},
  "MC":{"iso2":"MC","iso3":"MCO","phonecode":"377","region":"Europe"},
  "MN":{"iso2":"MN","iso3":"MNG","phonecode":"976","region":"Asia"},
  "MA":{"iso2":"MA","iso3":"MAR","phonecode":"212","region":"Africa"},
  "MZ":{"iso2":"MZ","iso3":"MOZ","phonecode":"258","region":"Africa"},
  "MM":{"iso2":"MM","iso3":"MMR","phonecode":"95","region":"Asia"},
  "NA":{"iso2":"NA","iso3":"NAM","phonecode":"264","region":"Africa"},
  "NR":{"iso2":"NR","iso3":"NRU","phonecode":"674","region":"Oceania"},
  "NP":{"iso2":"NP","iso3":"NPL","phonecode":"977","region":"Asia"},
  "NL":{"iso2":"NL","iso3":"NLD","phonecode":"31","region":"Europe"},
  "NZ":{"iso2":"NZ","iso3":"NZL","phonecode":"64","region":"Oceania"},
  "NI":{"iso2":"NI","iso3":"NIC","phonecode":"505","region":"Americas"},
  "NE":{"iso2":"NE","iso3":"NER","phonecode":"227","region":"Africa"},
  "NG":{"iso2":"NG","iso3":"NGA","phonecode":"234","region":"Africa"},
  "NO":{"iso2":"NO","iso3":"NOR","phonecode":"47","region":"Europe"},
  "OM":{"iso2":"OM","iso3":"OMN","phonecode":"968","region":"Asia"},
  "PK":{"iso2":"PK","iso3":"PAK","phonecode":"92","region":"Asia"},
  "PW":{"iso2":"PW","iso3":"PLW","phonecode":"680","region":"Oceania"},
  "PA":{"iso2":"PA","iso3":"PAN","phonecode":"507","region":"Americas"},
  "PG":{"iso2":"PG","iso3":"PNG","phonecode":"675","region":"Oceania"},
  "PY":{"iso2":"PY","iso3":"PRY","phonecode":"595","region":"Americas"},
  "PE":{"iso2":"PE","iso3":"PER","phonecode":"51","region":"Americas"},
  "PH":{"iso2":"PH","iso3":"PHL","phonecode":"63","region":"Asia"},
  "PL":{"iso2":"PL","iso3":"POL","phonecode":"48","region":"Europe"},
  "PT":{"iso2":"PT","iso3":"PRT","phonecode":"351","region":"Europe"},
  "QA":{"iso2":"QA","iso3":"QAT","phonecode":"974","region":"Asia"},
  "RO":{"iso2":"RO","iso3":"ROU","phonecode":"40","region":"Europe"},
  "RU":{"iso2":"RU","iso3":"RUS","phonecode":"7","region":"Europe"},
  "RW":{"iso2":"RW","iso3":"RWA","phonecode":"250","region":"Africa"},
  "KN":{"iso2":"KN","iso3":"KNA","phonecode":"1869","region":"Americas"},
  "LC":{"iso2":"LC","iso3":"LCA","phonecode":"1758","region":"Americas"},
  "VC":{"iso2":"VC","iso3":"VCT","phonecode":"1784","region":"Americas"},
  "WS":{"iso2":"WS","iso3":"WSM","phonecode":"685","region":"Oceania"},
  "SM":{"iso2":"SM","iso3":"SMR","phonecode":"378","region":"Europe"},
  "ST":{"iso2":"ST","iso3":"STP","phonecode":"239","region":"Africa"},
  "SA":{"iso2":"SA","iso3":"SAU","phonecode":"966","region":"Asia"},
  "SN":{"iso2":"SN","iso3":"SEN","phonecode":"221","region":"Africa"},
  "SC":{"iso2":"SC","iso3":"SYC","phonecode":"248","region":"Africa"},
  "SL":{"iso2":"SL","iso3":"SLE","phonecode":"232","region":"Africa"},
  "SG":{"iso2":"SG","iso3":"SGP","phonecode":"65","region":"Asia"},
  "SK":{"iso2":"SK","iso3":"SVK","phonecode":"421","region":"Europe"},
  "SI":{"iso2":"SI","iso3":"SVN","phonecode":"386","region":"Europe"},
  "SB":{"iso2":"SB","iso3":"SLB","phonecode":"677","region":"Oceania"},
  "SO":{"iso2":"SO","iso3":"SOM","phonecode":"252","region":"Africa"},
  "ZA":{"iso2":"ZA","iso3":"ZAF","phonecode":"27","region":"Africa"},
  "ES":{"iso2":"ES","iso3":"ESP","phonecode":"34","region":"Europe"},
  "LK":{"iso2":"LK","iso3":"LKA","phonecode":"94","region":"Asia"},
  "SD":{"iso2":"SD","iso3":"SDN","phonecode":"249","region":"Africa"},
  "SR":{"iso2":"SR","iso3":"SUR","phonecode":"597","region":"Americas"},
  "SZ":{"iso2":"SZ","iso3":"SWZ","phonecode":"268","region":"Africa"},
  "SE":{"iso2":"SE","iso3":"SWE","phonecode":"46","region":"Europe"},
  "CH":{"iso2":"CH","iso3":"CHE","phonecode":"41","region":"Europe"},
  "SY":{"iso2":"SY","iso3":"SYR","phonecode":"963","region":"Asia"},
  "TW":{"iso2":"TW","iso3":"TWN","phonecode":"886","region":"Asia"},
  "TJ":{"iso2":"TJ","iso3":"TJK","phonecode":"992","region":"Asia"},
  "TZ":{"iso2":"TZ","iso3":"TZA","phonecode":"255","region":"Africa"},
  "TH":{"iso2":"TH","iso3":"THA","phonecode":"66","region":"Asia"},
  "TL":{"iso2":"TL","iso3":"TLS","phonecode":"670","region":"Asia"},
  "TG":{"iso2":"TG","iso3":"TGO","phonecode":"228","region":"Africa"},
  "TO":{"iso2":"TO","iso3":"TON","phonecode":"676","region":"Oceania"},
  "TT":{"iso2":"TT","iso3":"TTO","phonecode":"1868","region":"Americas"},
  "TN":{"iso2":"TN","iso3":"TUN","phonecode":"216","region":"Africa"},
  "TR":{"iso2":"TR","iso3":"TUR","phonecode":"90","region":"Asia"},
  "TM":{"iso2":"TM","iso3":"TKM","phonecode":"993","region":"Asia"},
  "TV":{"iso2":"TV","iso3":"TUV","phonecode":"688","region":"Oceania"},
  "UG":{"iso2":"UG","iso3":"UGA","phonecode":"256","region":"Africa"},
  "UA":{"iso2":"UA","iso3":"UKR","phonecode":"380","region":"Europe"},
  "AE":{"iso2":"AE","iso3":"ARE","phonecode":"971","region":"Asia"},
  "GB":{"iso2":"GB","iso3":"GBR","phonecode":"44","region":"Europe"},
  "US":{"iso2":"US","iso3":"USA","phonecode":"1","region":"Americas"},
  "UY":{"iso2":"UY","iso3":"URY","phonecode":"598","region":"Americas"},
  "UZ":{"iso2":"UZ","iso3":"UZB","phonecode":"998","region":"Asia"},
  "VU":{"iso2":"VU","iso3":"VUT","phonecode":"678","region":"Oceania"},
  "VE":{"iso2":"VE","iso3":"VEN","phonecode":"58","region":"Americas"},
  "VN":{"iso2":"VN","iso3":"VNM","phonecode":"84","region":"Asia"},
  "YE":{"iso2":"YE","iso3":"YEM","phonecode":"967","region":"Asia"},
  "ZM":{"iso2":"ZM","iso3":"ZMB","phonecode":"260","region":"Africa"},
  "ZW":{"iso2":"ZW","iso3":"ZWE","phonecode":"263","region":"Africa"},
  // territorios especiales
  "AI":{"iso2":"AI","iso3":"AIA","phonecode":"1264","region":"Americas"},
  "AW":{"iso2":"AW","iso3":"ABW","phonecode":"297","region":"Americas"},
  "AN":{"iso2":"AN","iso3":"ANT","phonecode":"599","region":"Americas"},
  "KY":{"iso2":"KY","iso3":"CYM","phonecode":"1345","region":"Americas"},
  "CK":{"iso2":"CK","iso3":"COK","phonecode":"682","region":"Oceania"},
  "FO":{"iso2":"FO","iso3":"FRO","phonecode":"298","region":"Europe"},
  "GI":{"iso2":"GI","iso3":"GIB","phonecode":"350","region":"Europe"},
  "GL":{"iso2":"GL","iso3":"GRL","phonecode":"299","region":"Americas"},
  "IM":{"iso2":"IM","iso3":"IMN","phonecode":"44","region":"Europe"},
  "FK":{"iso2":"FK","iso3":"FLK","phonecode":"500","region":"Americas"},
  "MQ":{"iso2":"MQ","iso3":"MTQ","phonecode":"596","region":"Americas"},
  "MK":{"iso2":"MK","iso3":"MKD","phonecode":"389","region":"Europe"},
  "MS":{"iso2":"MS","iso3":"MSR","phonecode":"1664","region":"Americas"},
  "NC":{"iso2":"NC","iso3":"NCL","phonecode":"687","region":"Oceania"},
  "PN":{"iso2":"PN","iso3":"PCN","phonecode":"64","region":"Oceania"},
  "PR":{"iso2":"PR","iso3":"PRI","phonecode":"1787","region":"Americas"},
  "RE":{"iso2":"RE","iso3":"REU","phonecode":"262","region":"Africa"},
  "SH":{"iso2":"SH","iso3":"SHN","phonecode":"290","region":"Africa"},
  "PM":{"iso2":"PM","iso3":"SPM","phonecode":"508","region":"Americas"},
  "TC":{"iso2":"TC","iso3":"TCA","phonecode":"1649","region":"Americas"},
  "VG":{"iso2":"VG","iso3":"VGB","phonecode":"1284","region":"Americas"},
  "VI":{"iso2":"VI","iso3":"VIR","phonecode":"1340","region":"Americas"},
  "WF":{"iso2":"WF","iso3":"WLF","phonecode":"681","region":"Oceania"},
  "CS":{"iso2":"CS","iso3":"SCG","phonecode":"381","region":"Europe"},
}

function readJson<T>(file: string): T {
  const raw = readFileSync(join(JSON_DIR, file), 'utf-8')
  const parsed = JSON.parse(raw.charCodeAt(0) === 0xfeff ? raw.slice(1) : raw)
  const key = Object.keys(parsed)[0]
  return parsed[key] as T
}

// Mapa nombre (lowercase, sin acento) → iso2 para los países del JSON actual
const NAME_TO_ISO2: Record<string, string> = {
  "afganistan": "AF", "albania": "AL", "alemania": "DE", "algeria": "DZ",
  "andorra": "AD", "angola": "AO", "anguilla": "AG", "antigua y barbuda": "AG",
  "arabia saudita": "SA", "argentina": "AR", "armenia": "AM", "aruba": "AW",
  "australia": "AU", "austria": "AT", "azerbaiyan": "AZ", "bahamas": "BS",
  "bahrein": "BH", "bangladesh": "BD", "barbados": "BB", "belgica": "BE",
  "belice": "BZ", "benin": "BJ", "bielorusia": "BY", "birmania": "MM",
  "bolivia": "BO", "bosnia": "BA", "botsuana": "BW", "brasil": "BR",
  "brunei": "BN", "bulgaria": "BG", "burkina faso": "BF", "burundi": "BI",
  "butan": "BT", "cabo verde": "CV", "camboya": "KH", "camerun": "CM",
  "canada": "CA", "chad": "TD", "chile": "CL", "china": "CN",
  "chipre": "CY", "colombia": "CO", "comores": "KM", "congo brazzaville": "CG",
  "congo kinshasa": "CD", "corea del norte": "KP", "corea del sur": "KR",
  "cook islas": "CK", "costa de marfil": "CI", "costa rica": "CR",
  "croacia": "HR", "cuba": "CU", "dinamarca": "DK", "djibouti yibuti": "DJ",
  "dominica": "DM", "ecuador": "EC", "egipto": "EG", "el salvador": "SV",
  "emiratos arabes unidos": "AE", "eritrea": "ER", "eslovaquia": "SK",
  "eslovenia": "SI", "espana": "ES", "estados unidos": "US",
  "estonia": "EE", "etiopia": "ET", "feroe islas": "FO", "fiji": "FJ",
  "filipinas": "PH", "finlandia": "FI", "francia": "FR", "gabon": "GA",
  "gambia": "GM", "georgia": "GE", "ghana": "GH", "grecia": "GR",
  "granada": "GD", "guatemala": "GT", "guinea": "GN", "guinea bissau": "GW",
  "guinea ecuatorial": "GQ", "guyana": "GY", "haiti": "HT", "holanda": "NL",
  "honduras": "HN", "hungria": "HU", "india": "IN", "indonesia": "ID",
  "irak": "IQ", "iran": "IR", "irlanda": "IE", "islandia": "IS",
  "isla pitcairn": "PN", "islas caiman": "KY", "islas cook": "CK",
  "islas faroe": "FO", "islas malvinas": "FK", "islas marshall": "MH",
  "islas salomon": "SB", "islas turcas y caicos": "TC",
  "islas virgenes americanas": "VI", "islas virgenes britanicas": "VG",
  "israel": "IL", "italia": "IT", "jamaica": "JM", "japon": "JP",
  "jordania": "JO", "kazajstan": "KZ", "kenia": "KE", "kirguistan": "KG",
  "kiribati": "KI", "kuwait": "KW", "laos": "LA", "lesoto": "LS",
  "letonia": "LV", "libano": "LB", "liberia": "LR", "libia": "LY",
  "liechtenstein": "LI", "lituania": "LT", "luxemburgo": "LU",
  "macedonia": "MK", "madagascar": "MG", "malasia": "MY", "malawi": "MW",
  "maldivas": "MV", "mali": "ML", "malta": "MT", "man isla de": "IM",
  "marruecos": "MA", "mauricio": "MU", "mauritania": "MR", "mexico": "MX",
  "micronesia": "FM", "moldavia": "MD", "monaco": "MC", "mongolia": "MN",
  "mozambique": "MZ", "namibia": "NA", "nauru": "NR", "nepal": "NP",
  "nicaragua": "NI", "niger": "NE", "nigeria": "NG", "noruega": "NO",
  "nueva zelanda": "NZ", "oman": "OM", "paises bajos holanda": "NL",
  "pakistan": "PK", "palau": "PW", "panama": "PA", "papuanueva guinea": "PG",
  "paraguay": "PY", "peru": "PE", "polonia": "PL", "portugal": "PT",
  "qatar": "QA", "reino unido": "GB", "republica centroafricana": "CF",
  "republica checa": "CZ", "republica dominicana": "DO",
  "rumania": "RO", "rusia": "RU", "ruanda": "RW",
  "san cristobal y nevis": "KN", "san marino": "SM",
  "san tome y principe": "ST", "san vincente y granadinas": "VC",
  "santa elena": "SH", "santa lucia": "LC",
  "santo tome y principe": "ST", "senegal": "SN",
  "serbia y montenegro": "CS", "seychelles": "SC",
  "sierra leona": "SL", "singapur": "SG", "siria": "SY",
  "somalia": "SO", "sri lanka": "LK", "sudafrica": "ZA", "sudan": "SD",
  "suecia": "SE", "suiza": "CH", "surinam": "SR", "swazilandia": "SZ",
  "tadjikistan": "TJ", "tailandia": "TH", "taiwan": "TW", "tanzania": "TZ",
  "timor oriental": "TL", "togo": "TG", "tonga": "TO",
  "trinidad y tobago": "TT", "tunez": "TN", "turquia": "TR",
  "turkmenistan": "TM", "tuvalu": "TV", "ucrania": "UA", "uganda": "UG",
  "uruguay": "UY", "uzbekistan": "UZ", "vanuatu": "VU", "vaticano": "VA",
  "venezuela": "VE", "vietnam": "VN", "yemen": "YE", "zambia": "ZM",
  "zimbabue": "ZW", "antillas holandesas": "AN",
}

function normName(s: string): string {
  return s.toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9\s]/g, '').replace(/\s+/g, ' ').trim()
}

export async function seedGeo(prisma: PrismaClient) {
  console.log('  → Seeding geo data...')

  const countries: CountryJson[] = readJson('countries.json')
  const states: StateJson[]      = readJson('states.json')
  const cities: CityJson[]       = readJson('cities.json')

  // Países — todos, con ISO enriquecido
  await prisma.pais.createMany({
    data: countries.map(c => {
      const iso2 = NAME_TO_ISO2[normName(c.name)]
      const extra = iso2 ? DR5HN_ISO[iso2] : undefined
      return {
        idpaises:     c.id,
        nombrepaises: c.name,
        activo:       true,
        iso2:         extra?.iso2  ?? null,
        iso3:         extra?.iso3  ?? null,
        phonecode:    extra?.phonecode ?? null,
        region:       extra?.region    ?? null,
      }
    }),
    skipDuplicates: true,
  })
  console.log(`  ✓ Países: ${countries.length}`)

  // Departamentos — todos (activo solo para Colombia id=82)
  await prisma.departamento.createMany({
    data: states.map(s => ({
      iddepartamentos:     s.id,
      paises_idpaises:     s.id_country,
      nombredepartamentos: s.name,
      activo:              s.id_country === 82,
    })),
    skipDuplicates: true,
  })
  console.log(`  ✓ Departamentos: ${states.length}`)

  // Ciudades — solo Colombia (id_country = 82), todas activas
  const colStates = new Set(states.filter(s => s.id_country === 82).map(s => s.id))
  const colCities = cities.filter(c => colStates.has(c.id_state))

  const BATCH = 500
  for (let i = 0; i < colCities.length; i += BATCH) {
    await prisma.ciudad.createMany({
      data: colCities.slice(i, i + BATCH).map(c => ({
        idciudades:                    c.id,
        departamentos_iddepartamentos: c.id_state,
        nombreciudades:                c.name,
        activo:                        true,
      })),
      skipDuplicates: true,
    })
  }
  console.log(`  ✓ Ciudades Colombia: ${colCities.length}`)
}
